export ZSH="/home/duy/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

autoload -U colors && colors	# Load colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "
setopt autocd	
stty stop undef

# Path to your oh-my-zsh installation.
HISTSIZE=10000
unsetopt HIST_VERIFY

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

plugins=(git)

if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

export LANG=en_US.UTF-8
export EDITOR='nvim'

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH
export BAT_THEME="TwoDark"

printer_setup(){
	setopt +o nomatch
	for f in /dev/usb/lp*; do
		if [ -e "$f" ]; then
			echo "Restarting org.cups.cupsd.service..."
			sudo systemctl restart org.cups.cupsd.service
			echo "Configuring printer..."
			sudo /usr/bin/lpadmin -p LBP2900 -m CNCUPSLBP2900CAPTK.ppd -v ccp://localhost:59687 -E
			sudo /usr/bin/ccpdadmin -p LBP2900 -o $f
			echo "Restarting ccpd.service..."
			sudo systemctl restart ccpd.service
			echo "Done!"
		else
			echo "Looks like No printer attached"
		fi
		break
	done
	unsetopt +o nomatch
}
